---
- name: Creacion de nuevo contenedor 
  proxmox:
    vmid: "{{ vmid }}"
    node: "{{ node }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    hostname: "{{ hostname }}" 
    #password: "{{ password }}"
    unprivileged: yes
    ostemplate: "{{ ostemplate }}"
    storage: "{{ storage }}"
    cores: 1
    pubkey: "{{ pubkey }}" 
    disk: "{{ disk }}"
    memory: "{{ memory }}"
    onboot: yes
    netif: '{"net0":"name=eth0,ip=dhcp,ip6=dhcp,bridge=vmbr0"}'
